DLPX-86537 CIS: sudoers configuration
delphix/delphix-platform pull request #498
Opened 2024-09-30 15:17 UTC by dbshah12

<details open>
<summary><h2> Problem </h2></summary>

Provide a clear description of the high-level problem you are trying to
solve. The problem statement should be written in terms of a specific
symptom that affects users or the business. The problem statement should
not be written in terms of the solution. If possible, include a minimal
reproducible example (MRE) with steps to reproduce, expected results,
and actual results.
</details>

<details open>
<summary><h2> Solution </h2></summary>

Provide a clear description of the high-level solution you have chosen.
If there were other possible solutions that you considered and rejected,
mention those along with the corresponding reasoning. Do not describe
implementation details when writing about the solution; these should go
into the implementation section instead.
</details>

<details>
<summary><h2> Testing Done </h2></summary>

Provide a clear description of how this change was tested. At minimum
this should include proof that a computer has executed the changed
lines. Ideally this should include an automated test or an explanation
as to why this pull request has no tests.
</details>

2024-10-03 14:11 UTC, sebroy requested changes
We should not be making these changes using ansible. The idea of the "*.d" directories is that they can contain configuration fragments as files. You can simply include the files you want in the delphix-platform repo. For example, see how we already provide such a configuration fragment in the repo already in a file called `delphix`. We can do the same for logrotate configuration fragments.

2024-10-03 14:23 UTC, dbshah12 commented
> We should not be making these changes using ansible. The idea of the "*.d" directories is that they can contain configuration fragments as files. You can simply include the files you want in the delphix-platform repo. For example, see how we already provide such a configuration fragment in the repo already in a file called `delphix`. We can do the same for logrotate configuration fragments.

Ohh yeah, I wasn't aware of it, I used `delphix` file to set below 2

```
Defaults use_pty
Defaults logfile='/var/log/sudo.log'
```

And also added a log rotator, @sebroy thanks for suggesting, can you please re-review? I will do testing again once, the pre-push completes.

2024-10-04 14:08 UTC, dbshah12 commented
> > We should not be making these changes using ansible. The idea of the "*.d" directories is that they can contain configuration fragments as files. You can simply include the files you want in the delphix-platform repo. For example, see how we already provide such a configuration fragment in the repo already in a file called `delphix`. We can do the same for logrotate configuration fragments.
> 
> Ohh yeah, I wasn't aware of it, I used `delphix` file to set below 2
> 
> ```
> Defaults use_pty
> Defaults logfile='/var/log/sudo.log'
> ```
> 
> And also added a log rotator, @sebroy thanks for suggesting, can you please re-review? I will do testing again once, the pre-push completes.

@sebroy Completed the normal and upgrade testing, things are working as expected, can you please re-review?

2024-10-04 14:17 UTC, sebroy approved these changes
one last nit: we should be consistent with copyright blocks. In this case, one file has a copyright block, and the other does not. Either they should both have one, or neither should have one. IMO configuration files are not copyrightable code, and should not have a copyright block. As such, I suggest removing the copyright block from the sudoers.d file to make things consistent.

2024-10-04 14:40 UTC, dbshah12 commented
> one last nit: we should be consistent with copyright blocks. In this case, one file has a copyright block, and the other does not. Either they should both have one, or neither should have one. IMO configuration files are not copyrightable code, and should not have a copyright block. As such, I suggest removing the copyright block from the sudoers.d file to make things consistent.

Yes, that's a good idea. However, I was thinking about something else:

I searched for the files with `# Licensed under the Apache License`, and all of them include a copyright notice. Should we consider adding this instead of removing it?

2024-10-04 17:15 UTC, nealquigley approved these changes
LGTM. I don't have strong feelings nor expertise in copyrights but per your comment, it seems like adding the same sort of block to the new file would be more consistent with the rest of the codebase than removing it from the preexisting file.

2024-10-07 03:12 UTC, dbshah12 commented
> LGTM. I don't have strong feelings nor expertise in copyrights but per your comment, it seems like adding the same sort of block to the new file would be more consistent with the rest of the codebase than removing it from the preexisting file.

- Yeah, I agree with you on consistency but as @sebroy suggested `configuration files are not copyrightable code` so I removed it.

2024-10-07 16:23 UTC, merged